Repository openstack-k8s-operators/openstack-baremetal-operator, pull requests merged in 2024-02, with the labels that each got.

#125 This change ensures the baremetal-operator is built with FIPS compliance
  .prow_ci.env
  Dockerfile
  Makefile
Labels: lgtm, approved

#126 Expose provision server images in baremetal set
  api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
  api/v1beta1/openstackbaremetalset_types.go
  config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
  controllers/openstackbaremetalset_controller.go
Labels: lgtm, approved

#124 Controller runtime update
  .ci-operator.yaml
  .github/workflows/build-openstack-baremetal-operator.yaml
  .github/workflows/golangci-lint.yaml
  Dockerfile
  api/bases/baremetal.openstack.org_openstackprovisionservers.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/openstackbaremetalset_webhook.go
  api/v1beta1/openstackprovisionserver_webhook.go
  config/crd/bases/baremetal.openstack.org_openstackprovisionservers.yaml
  controllers/openstackbaremetalset_controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm

#130 Remove golangci-lint github action
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  .pre-commit-config.yaml
Labels: approved

#73 Bump metal3 baremetal-operator to v0.5.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, approved

#131 [renovate]Remove golang constraint
  renovate.json
Labels: lgtm, approved

#128 Sync EnvTest version with k8s version
  Makefile
Labels: lgtm, approved

#129 Add IPv6 support for networkdata
  api/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
  api/v1beta1/openstackbaremetalset_types.go
  config/crd/bases/baremetal.openstack.org_openstackbaremetalsets.yaml
  config/samples/baremetal_v1beta1_openstackbaremetalset.yaml
  pkg/openstackbaremetalset/baremetalhost.go
  templates/openstackbaremetalset/cloudinit/networkdata
Labels: lgtm, approved

#137 Build agent with golang 1.20
  Dockerfile.agent
Labels: lgtm, approved

#138 Regenerate go.mod indirect dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, approved
